feat(toolshed): add double buffer and buffer queue
edgeandnode/toolshed pull request #66
Opened 2023-12-20 13:20 UTC by Jannis

This adds two utilities from the gateway codebase that I'd like to move here to avoid cyclic dependencies within the gateway crates.

2023-12-20 14:14 UTC, LNSD requested changes
Some of the types added in this PR to `toolshed` crate should be added in the `thegraph` crate instead.

----

As a rule of thumb, we are adding the common and fundamental (a.k.a. _primitive_) types under the `thegraph` crate. Other utilities are ok under the toolshed.

2023-12-20 14:14 UTC, LNSD commented on toolshed/src/tokens.rs
I think this module, `tokens`, is a good candidate to be included in `thegraph::types` module since it contains types likely used across the different E&N rust projects (e.g., Gateway).

2023-12-20 14:14 UTC, LNSD commented on toolshed/src/decimal.rs
I think this module, `decimal`, is a good candidate to be included in the `thegraph::types::primitives` module since it contains types likely used across the different E&N rust projects (e.g., Gateway) and are fundamental building blocks for other types in this case, the `tokens` types.

2023-12-20 15:07 UTC, Theodus commented on toolshed/src/tokens.rs
I'm not sure we want to include this module as-is for just `GRT` & `USD` types. It's cumbersome by design. And I don't think it provides a lot of value. It's also trivial.

2023-12-20 15:48 UTC, LNSD commented on toolshed/src/tokens.rs
Agree 👍🏼 

Maybe we can add only the `decimal` part in the `thegraph::types::primitives` as a first step. And let's see if we want to include these `token` types in the future.

2023-12-21 08:50 UTC, Jannis commented
@LNSD By that logic, shouldn't the epoch cache also live in `thegraph`?

2023-12-21 10:07 UTC, Jannis commented
@LNSD Ok, this is good to review now.

2023-12-21 10:08 UTC, Jannis commented on toolshed/src/decimal.rs
Done!

2023-12-21 10:19 UTC, Jannis commented on toolshed/src/tokens.rs
@Theodus The tricky bit is that both `gateway-common` and `indexer-selection` need it and `gateway-common` depends on `indexer-selection`. Could put it into indexer-selection, but that doesn't feel right.

2023-12-21 10:45 UTC, Jannis commented on toolshed/src/tokens.rs
I'll put it into indexer-selection for the moment.

2023-12-21 11:32 UTC, LNSD approved these changes
LGTM ✅

2023-12-21 11:32 UTC, LNSD commented on thegraph/src/types/primitives/decimal.rs
> +pub struct InvalidDecimalString;
I just noticed that this type is a struct representing an error but it does not implement the `std::error::Error` trait 👀 

It's not blocking for this PR, but it's definitely something to fix in the near future

2023-12-21 11:37 UTC, LNSD commented
> @LNSD By that logic, shouldn't the epoch cache also live in `thegraph`?

I differentiate between _fundamental types_, which I see as "scalar types" (e.g., DeploymentId, SubgraphId, etc.), and _utility types_, which typically are utility data structures (e.g., epoch cache, linked lists, etc.).

But this is the ruleset I have been applying so far. We can agree on another ruleset, if we find this one limiting 🤷🏼‍♂️ 🙂

2023-12-21 11:53 UTC, LNSD commented
> @Theodus The tricky bit is that both `gateway-common` and `indexer-selection` need it and `gateway-common` depends on `indexer-selection`. Could put it into indexer-selection, but that doesn't feel right.

As a side note, in the projects I have worked on modularizing and generalizing a prototype, we ended up with typically these modules:

- **common**: The common module containing types and structures common to all the modules in the monorepo. It is the "origin" crate of the dependency graph.
- **core**: The module that contains the modules that have been generalized from the initial prototype implementation. It is the framework module/crate. It is imported by the different specific implementations.
- **<core-modules>**: If a core component has enough entity and complexity to have its own module, it is extracted into a separate module. This would be the case of the indexer selection module.
- **<app-modules>**: The different apps built on top of the _core_ module. If the prototype is generalized, it is included in this category as another implementation.

This setup worked very well if we respected the following ruleset:

> * The `common` module MUST NOT import any module in the monorepo.
> * The `core` module, or any other `<core-modules>`, CAN import the `common` module.
> * The `<core-modules>` CAN import the `core` module.
> * The `core` module MUST NOT import the `<core-modules>`.
> * The `<app-modules>` CAN import the `common`, `core` and `<core-modules>`.
> * The `<app-modules>` MUST NOT be imported by any module within the monorepo.

The idea is that this setup creates an acyclic dependency graph where the `common` and `<app-modules>` are terminal modules.

2023-12-21 12:36 UTC, Jannis commented
> > @Theodus The tricky bit is that both `gateway-common` and `indexer-selection` need it and `gateway-common` depends on `indexer-selection`. Could put it into indexer-selection, but that doesn't feel right.
> 
> As a side note, in the projects I have worked on modularizing and generalizing a prototype, we ended up with typically these modules:
> 
> * **common**: The common module containing types and structures common to all the modules in the monorepo. It is the "origin" crate of the dependency graph.
> * **core**: The module that contains the modules that have been generalized from the initial prototype implementation. It is the framework module/crate. It is imported by the different app implementations.
> * **<core-modules>**: If a core component has enough entity and complexity to have its own module, it is extracted into a separate module. This would be the case for the indexer selection module.
> * **<app-modules>**: The different apps built on top of the _core_ module. The prototype pertains to this category as another implementation.
> 
> This setup worked very well if we respected the following ruleset:
> 
> > * The `common` module MUST NOT import any module in the monorepo.
> > * The `core` module, or any other `<core-modules>`, CAN import the `common` module.
> > * The `<core-modules>` CAN import the `core` module.
> > * The `core` module MUST NOT import the `<core-modules>`.
> > * The `<app-modules>` CAN import the `common`, `core`, and `<core-modules>`.
> > * The `<app-modules>` MUST NOT be imported by any module within the monorepo.
> 
> The idea is that this setup creates an acyclic dependency graph where the `common` and `<app-modules>` are terminal modules.

That makes a lot of sense. Let's think about that some more for the gateway.

2023-12-21 12:36 UTC, merged